theme: jekyll-theme-dinky
# the "repository:" line makes octocat not barf when the repo is checked out from windows git but we're running jekyll under linux (in a VM using a shared folder) - if it's not present, it'll try to use the local repo, which will be the wrong format
repository: clavister-docs/kb
exclude:
  - CNAME
  - README.MD
  - README.md
  - "*.sh"
  - "*.bat"
  - "*.BAT"
  - Gemfile
  - Gemfile.lock
